import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AuthContextProvider from "./context/AuthContext";
import CartContextProvider from "./context/CartContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nike",
  description: "Generated by create next app",
  keywords: ["nike", "zapatillas", "accesorios", "jordan", "ropa"]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider>
          <AuthContextProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
